from typing import List, Dict, Optional
from pydantic import BaseModel, Field


class PerformanceMetrics(BaseModel):
    preprocess_ms: float = Field(..., description="Image loading and preprocessing time in milliseconds")
    inference_ms: float = Field(..., description="Model forward-pass latency in milliseconds")
    postprocess_ms: float = Field(..., description="Non-maximum suppression and filtering latency in milliseconds")
    total_ms: float = Field(..., description="End-to-end processing latency in milliseconds")
    device: str = Field(default="cpu", description="Compute device used (cpu or cuda)")


class BoundingBox(BaseModel):
    class_id: int = Field(..., description="COCO class identifier integer")
    class_name: str = Field(..., description="Human-readable object name")
    confidence: float = Field(..., description="Detection confidence score between 0.0 and 1.0")
    box: List[int] = Field(..., description="Bounding box pixel coordinates [x1, y1, x2, y2]")
    normalized_centroid: List[float] = Field(..., description="Normalized center coordinates [cx, cy]")


class DetectionResponse(BaseModel):
    total_objects: int = Field(..., description="Total number of objects detected after thresholding")
    unique_classes: int = Field(..., description="Number of unique object classes present")
    average_confidence: float = Field(..., description="Average confidence score across all detected objects")
    image_width: int = Field(..., description="Original image width in pixels")
    image_height: int = Field(..., description="Original image height in pixels")
    class_counts: Dict[str, int] = Field(..., description="Frequency count per object class")
    detections: List[BoundingBox] = Field(default_factory=list, description="List of detected bounding boxes")
    annotated_image_base64: Optional[str] = Field(None, description="Base64 encoded JPEG with annotated bounding boxes")
    metrics: PerformanceMetrics


class DistanceItem(BaseModel):
    obj1: str = Field(..., description="Primary object name")
    obj2: str = Field(..., description="Secondary object name")
    distance: float = Field(..., description="Normalized Euclidean distance on image plane")
    proximity: str = Field(..., description="Categorical proximity rating: Very Close, Close, or Far")


class DistanceResponse(BaseModel):
    total_pairs: int = Field(..., description="Total pairwise relations calculated")
    distances: List[DistanceItem] = Field(default_factory=list, description="Top proximity pairs sorted by distance")


class SceneDescriptionResponse(BaseModel):
    description: str = Field(..., description="Natural language scene description generated by Gemini")
    detected_context: str = Field(..., description="Summary of objects passed into the LLM prompt")


class RiskAssessmentResponse(BaseModel):
    overall_risk: str = Field(..., description="Overall risk level: Low, Medium, or High")
    key_risks: List[str] = Field(default_factory=list, description="Identified risk points")
    recommendations: List[str] = Field(default_factory=list, description="Mitigation recommendations")
    raw_text: str = Field(..., description="Full text response from Gemini safety assessment")


class QARequest(BaseModel):
    question: str = Field(..., description="User question to ask about the uploaded image")


class QAResponse(BaseModel):
    question: str = Field(..., description="The query asked")
    answer: str = Field(..., description="Answer grounded in visual perception and detection data")


class ClassDelta(BaseModel):
    object: str = Field(..., description="Object class name")
    image1_count: int = Field(..., description="Count of occurrences in Image 1")
    image2_count: int = Field(..., description="Count of occurrences in Image 2")
    change: int = Field(..., description="Delta (Image 2 - Image 1)")


class ComparisonResponse(BaseModel):
    image1_total: int = Field(..., description="Total objects detected in Image 1")
    image2_total: int = Field(..., description="Total objects detected in Image 2")
    changes: List[ClassDelta] = Field(default_factory=list, description="Object count comparisons sorted by magnitude of change")
    metrics: PerformanceMetrics


class BatchDetectionItem(BaseModel):
    filename: str = Field(..., description="Uploaded image filename")
    total_objects: int = Field(..., description="Number of detected objects")
    unique_classes: int = Field(..., description="Count of unique object classes")
    class_counts: Dict[str, int] = Field(..., description="Frequency of each detected class")
    average_confidence: float = Field(..., description="Mean confidence score")
    metrics: PerformanceMetrics


class BatchDetectionResponse(BaseModel):
    total_images_processed: int = Field(..., description="Number of images analyzed in the batch")
    results: List[BatchDetectionItem] = Field(default_factory=list, description="Per-image analysis summaries")
    total_processing_time_ms: float = Field(..., description="Cumulative execution time in milliseconds")


class FullAnalysisExport(BaseModel):
    system_version: str = Field(..., description="API Version")
    detection_summary: DetectionResponse
    distances: List[DistanceItem]
    scene_description: Optional[str] = None
    risk_assessment: Optional[RiskAssessmentResponse] = None
